"""Add foreign keys to booking model

Revision ID: ec378d5fee20
Revises: b2d63b3202ee
Create Date: 2025-11-10 11:50:27.397879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec378d5fee20'
down_revision = 'b2d63b3202ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stylist_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_booking_customer_id', 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key('fk_booking_stylist_id', 'stylist', ['stylist_id'], ['id'])
        batch_op.create_foreign_key('fk_booking_service_id', 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_service_id', type_='foreignkey')
        batch_op.drop_constraint('fk_booking_stylist_id', type_='foreignkey')
        batch_op.drop_constraint('fk_booking_customer_id', type_='foreignkey')
        batch_op.drop_column('stylist_id')
        batch_op.drop_column('service_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
